os:
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
gui:
  ## stuff relating to the UI
  scrollHeight: 2
  scrollPastBottom: true
  mouseEvents: true
  skipUnstageLineWarning: false
  skipStashWarning: true
  showIcons: true
  sidePanelWidth: 0.3333
  theme:
    lightTheme: false
    activeBorderColor:
      - green
      - bold
    inactiveBorderColor:
      - white
    optionsTextColor:
      - blue
    selectedLineBgColor:
      - black
    selectedRangeBgColor:
      - blue
  commitLength:
    show: true
services:
  "github-work": "github:github.com"
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never --24-bit-color=never
  merging:
    manualCommit: false
    args: ""
  skipHookPrefix: "WIP"
  autoFetch: true
update:
  method: prompt # can be: prompt | background | never
  days: 14 # how often a update is checked for
reporting: "off"
startuppopupversion: 1
splashUpdatesIndex: 0
confirmOnQuit: false
keybinding:
  universal:
    quit: "q"
    quit-alt1: "<c-c>"
    return: "<esc>"
    quitWithoutChangingDirectory: "Q"
    togglePanel: "<tab>"
    prevItem: "<up>"
    nextItem: "<down>"
    prevItem-alt: "k"
    nextItem-alt: "j"
    prevPage: ","
    nextPage: "."
    gotoTop: "<"
    gotoBottom: ">"
    prevBlock: "<left>"
    nextBlock: "<right>"
    prevBlock-alt: "h"
    nextBlock-alt: "l"
    nextMatch: "n"
    prevMatch: "N"
    startSearch: "/"
    optionMenu: "x"
    optionMenu-alt1: "?"
    select: "<space>"
    goInto: "<enter>"
    remove: "d"
    new: "n"
    edit: "e"
    openFile: "o"
    scrollUpMain: "<pgup>"
    scrollDownMain: "<pgdown>"
    scrollUpMain-alt1: "K"
    scrollDownMain-alt1: "J"
    scrollUpMain-alt2: "<c-u>"
    scrollDownMain-alt2: "<c-d>"
    executeCustomCommand: ":"
    createRebaseOptionsMenu: "m"
    pushFiles: "P"
    pullFiles: "p"
    refresh: "R"
    createPatchOptionsMenu: "<c-p>"
    nextTab: "]"
    prevTab: "["
    nextScreenMode: "+"
    prevScreenMode: "_"
    undo: "z"
    redo: "<c-z>"
    filteringMenu: <c-s>
    diffingMenu: "<c-e>"
    copyToClipboard: "<c-o>"
  status:
    checkForUpdate: "u"
    recentRepos: "<enter>"
  files:
    commitChanges: "c"
    commitChangesWithoutHook: "w"
    amendLastCommit: "A"
    commitChangesWithEditor: "C"
    ignoreFile: "i"
    refreshFiles: "r"
    stashAllChanges: "s"
    viewStashOptions: "S"
    toggleStagedAll: "a"
    viewResetOptions: "D"
    fetch: "f"
  branches:
    createPullRequest: "o"
    checkoutBranchByName: "c"
    forceCheckoutBranch: "F"
    rebaseBranch: "r"
    renameBranch: "R"
    mergeIntoCurrentBranch: "M"
    viewGitFlowOptions: "i"
    fastForward: "f"
    pushTag: "P"
    setUpstream: "u"
    fetchRemote: "f"
  commits:
    squashDown: "s"
    renameCommit: "r"
    renameCommitWithEditor: "R"
    viewResetOptions: "g"
    markCommitAsFixup: "f"
    createFixupCommit: "F"
    squashAboveCommits: "S"
    moveDownCommit: "<c-j>"
    moveUpCommit: "<c-k>"
    amendToCommit: "A"
    pickCommit: "p"
    revertCommit: "t"
    cherryPickCopy: "c"
    cherryPickCopyRange: "C"
    pasteCommits: "v"
    tagCommit: "T"
    checkoutCommit: "<space>"
    resetCherryPick: "<c-R>"
  stash:
    popStash: "g"
  commitFiles:
    checkoutCommitFile: "c"
  main:
    toggleDragSelect: "v"
    toggleDragSelect-alt: "V"
    toggleSelectHunk: "a"
    pickBothHunks: "b"
