# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'


# icon options = ïƒš â¯ ï„ ï„… ï¡
# Top left:     directory(gitbranch) â— â—

format = """
$directory(bold green)(\\($git_branch\\)) $git_status\
$git_commit\
$git_state\
$line_break\
$jobs\
$character
"""

right_format = "$all $time"
# Remove the newline that separates prompts, it eats up too much space
add_newline = false

[character]
format = "$symbol "
success_symbol = "[âœ](bold purple) "
error_symbol = "[âœ—](bold red) "
vicmd_symbol = "[î˜«](#137628) "

[time]
format = "[$time]($style)"
style = "dimmed #818181"
disabled = false

[git_status]
format = """
([\
($conflicted )\
[($stashed )](yellow)\
$deleted\
($renamed )\
[($modified )](green)\
$staged\
$untracked\
[$ahead_behind](yellow)\
]($style) )"""
stashed = "ïŸº"
modified = "â—"

[git_branch]
format = "[$branch(:$remote_branch)]($style)"
style = "italic blue"
symbol = "ï˜ "

[directory]
format = "[$path]($style)[$read_only]($read_only_style)"
style = "bold green"
read_only = " ï ½"

[gcloud]
symbol = "ï† "
disabled = true

[lua]
symbol = "î˜  "
format = " [$symbol($version)]($style)"

[golang]
symbol = "î˜§ "
format = "[$symbol($version)]($style)"

[aws]
symbol = "îŒ½  "

[buf]
symbol = "ï’ "

[c]
symbol = "î˜ "

[conda]
symbol = "ï„Œ "

[dart]
symbol = "î˜ "

[docker_context]
symbol = "ïŒˆ "

[elixir]
symbol = "î‰µ "

[elm]
symbol = "î˜¬ "

[haskell]
symbol = "î· "

[java]
symbol = "î‰– "

[julia]
symbol = "î˜¤ "

[memory_usage]
symbol = "ï¡š "

[nim]
symbol = "ïš¤ "

[nix_shell]
symbol = "ï‹œ "

[nodejs]
symbol = "îœ˜ "

[package]
symbol = "ï£– "

[python]
symbol = "îˆµ "

[spack]
symbol = "ğŸ…¢ "

[rust]
symbol = "î¨ "
