# Configuration for Alacritty, the GPU enhanced terminal emulator.

# Any items in the `env` entry below will be added as
# environment variables. Some entries may override variables
# set by alacritty itself.
env:
  # TERM variable
  #
  # This value is used to set the `$TERM` environment variable for
  # each instance of Alacritty. If it is not present, alacritty will
  # check the local terminfo database and use 'alacritty' if it is
  # available, otherwise 'xterm-256color' is used.
  TERM: xterm-256color

window:
  # Window dimensions (changes require restart)
  #
  # Specified in number of columns/lines, not pixels.
  # If both are `0`, this setting is ignored.
  dimensions:
    columns: 80
    lines: 24

  # Window padding (changes require restart)
  #
  # Blank space added around the window in pixels. This padding is scaled
  # by DPI and the specified value is always added at both opposing sides.
  padding:
    x: 2
    y: 0

  # Spread additional padding evenly around the terminal content.
  dynamic_padding: false

  # Window decorations
  #
  # Available values:
  # - `full`: Window with title bar and title bar buttons
  # - `none`: Window without title bar, rounded corners, or drop shadow
  # - `transparent`: Window with title bar with transparent background and title
  #   bar buttons
  # - `buttonless`: Window with title bar with transparent background and no
  #   title bar buttons
  # Window decorations
  #
  # Values for `decorations`:
  #     - full: Borders and title bar
  #     - none: Neither borders nor title bar
  #     - buttonless: Title bar, transparent background and title bar buttons
  #     - transparent: Title bar, transparent background, but no title bar buttons
  decorations: transparent

scrolling:
  # Maximum number of lines in the scrollback buffer.
  # Specifying '0' will disable scrolling.
  history: 10000

  # Number of lines the viewport will move for every line scrolled when
  # scrollback is enabled (history > 0).
  multiplier: 3

# Font configuration (changes require restart)
font:
  # Normal (roman) font face
  normal:
    family: FiraCode Nerd Font
    # The `style` can be specified to pick a specific face.
    style: Retina

  # Bold font face
  bold:
    family: Operator Mono
    # The `style` can be specified to pick a specific face.
    style: Bold Italic

  # Italic font face
  italic:
    family: Operator Mono Book

  # Point size
  size: 17.0

  # Offset is the extra space around each character. `offset.y` can be thought of
  # as modifying the line spacing, and `offset.x` as modifying the letter spacing.
  offset:
    x: 0
    y: 0

  # Glyph offset determines the locations of the glyphs within their cells with
  # the default being at the bottom. Increasing `x` moves the glyph to the right,
  # increasing `y` moves the glyph upwards.
  glyph_offset:
    x: 0
    y: 0

  # Thin stroke font rendering (OS X only)
  #
  # Thin strokes are suitable for retina displays, but for non-retina screens
  # it is recommended to set `use_thin_strokes` to `false`
  use_thin_strokes: false

# If `true`, bold text is drawn using the bright color variants.
draw_bold_text_with_bright_colors: true

# background-color (Night Owl) '0x011627'
# background-color (One Dark) '0x282c34'
# Colors (One Dark)
#

# Colors (Monokai Dark)
colors:
  # Default colors
  primary:
    background: "0x262626"
    foreground: "0xF8F8F2"

  # Normal colors
  normal:
    black: "0x272822"
    red: "0xF92672"
    green: "0xA6E22E"
    yellow: "0xF4BF75"
    blue: "0x66D9EF"
    magenta: "0xAE81FF"
    cyan: "0xA1EFE4"
    white: "0xF8F8F2"

  # Bright colors
  bright:
    black: "0x75715E"
    red: "0xF92672"
    green: "0xA6E22E"
    yellow: "0xF4BF75"
    blue: "0x66D9EF"
    magenta: "0xAE81FF"
    cyan: "0xA1EFE4"
    white: "0xF9F8F5"

  # colors:
  #   # Default colors
  #   primary:
  #     background: "0x282c34"
  #     foreground: "0xabb2bf"
  #   # Normal colors
  #   normal:
  #     # NOTE: Use '0x131613' for the `black` color if you'd like to see
  #     # black text on the background.
  #     black: "0x282c34"
  #     red: "0xe06c75"
  #     green: "0x98c379"
  #     yellow: "0xd19a66"
  #     blue: "0x61afef"
  #     magenta: "0xc678dd"
  #     cyan: "0x56b6c2"
  #     white: "0xabb2bf"
  #   # Bright colors
  #   bright:
  #     black: "0x5c6370"
  #     red: "0xe06c75"
  #     green: "0x98c379"
  #     yellow: "0xd19a66"
  #     blue: "0x61afef"
  #     magenta: "0xc678dd"
  #     cyan: "0x56b6c2"
  #     white: "0xffffff"
  # Colors (Tomorrow Night Bright)
  # colors:
  #   # Default colors
  #   primary:
  #     background: '0x000000'
  #     foreground: '0xeaeaea'
  #
  #     # Bright and dim foreground colors
  #     #
  #     # The dimmed foreground color is calculated automatically if it is not present.
  #     # If the bright foreground color is not set, or `draw_bold_text_with_bright_colors`
  #     # is `false`, the normal foreground color will be used.
  #     #dim_foreground: '0x9a9a9a'
  #     #bright_foreground: '0xffffff'
  #
  #   # Cursor colors
  #   #
  #   # Colors which should be used to draw the terminal cursor. If these are unset,
  #   # the cursor color will be the inverse of the cell color.
  #   #cursor:
  #   #  text: '0x000000'
  #   #  cursor: '0xffffff'
  #
  #   # Normal colors
  #   normal:
  #     black:   '0x000000'
  #     red:     '0xd54e53'
  #     green:   '0xb9ca4a'
  #     yellow:  '0xe6c547'
  #     blue:    '0x7aa6da'
  #     magenta: '0xc397d8'
  #     cyan:    '0x70c0ba'
  #     white:   '0xffffff'
  #
  #   # Bright colors
  #   bright:
  #     black:   '0x666666'
  #     red:     '0xff3334'
  #     green:   '0x9ec400'
  #     yellow:  '0xe7c547'
  #     blue:    '0x7aa6da'
  #     magenta: '0xb77ee0'
  #     cyan:    '0x54ced6'
  #     white:   '0xffffff'
  # Dim colors
  #
  # If the dim colors are not set, they will be calculated automatically based
  # on the `normal` colors.
  # dim:
  #   black: "0x333333"
  #   red: "0xf2777a"
  #   green: "0x99cc99"
  #   yellow: "0xffcc66"
  #   blue: "0x6699cc"
  #   magenta: "0xcc99cc"
  #   cyan: "0x66cccc"
  #   white: "0xdddddd"
  # Indexed Colors
  #
  # The indexed colors include all colors from 16 to 256.
  # When these are not set, they're filled with sensible defaults.
  #indexed_colors:
  #  - { index: 16, color: '0x000000' }

# Visual Bell
#
# Any time the BEL code is received, Alacritty "rings" the visual bell. Once
# rung, the terminal background will be set to white and transition back to the
# default background color. You can control the rate of this transition by
# setting the `duration` property (represented in milliseconds). You can also
# configure the transition function by setting the `animation` property.
#
# Values for `animation`:
#   - Ease
#   - EaseOut
#   - EaseOutSine
#   - EaseOutQuad
#   - EaseOutCubic
#   - EaseOutQuart
#   - EaseOutQuint
#   - EaseOutExpo
#   - EaseOutCirc
#   - Linear
#
# Specifying a `duration` of `0` will disable the visual bell.
visual_bell:
  animation: EaseOutExpo
  duration: 0

# Background opacity
#
# Window opacity as a floating point number from `0.0` to `1.0`.
# The value `0.0` is completely transparent and `1.0` is opaque.
background_opacity: 1.0

# Mouse bindings
#
# Available fields:
# - mouse
# - action
# - mods (optional)
#
# Values for `mouse`:
# - Middle
# - Left
# - Right
# - Numeric identifier such as `5`
#
# All available `mods` and `action` values are documented in the key binding
# section.
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  # Click settings
  #
  # The `double_click` and `triple_click` settings control the time
  # alacritty should wait for accepting multiple clicks as one double
  # or triple click.
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

  # If this is `true`, the cursor is temporarily hidden when typing.
  hide_when_typing: false

  url:
    # URL launcher
    #
    # This program is executed when clicking on a text which is recognized as a URL.
    # The URL is always added to the command as the last parameter.
    #
    # When set to `launcher: None`, URL launching will be disabled completely.
    #
    # Default:
    #   - (macOS) open
    #   - (Linux/BSD) xdg-open
    #   - (Windows) explorer
    #launcher:
    #  program: xdg-open
    #  args: []

    # URL modifiers
    #
    # These are the modifiers that need to be held down for opening URLs when clicking
    # on them. The available modifiers are documented in the key binding section.
    modifiers: Control|Shift

selection:
  semantic_escape_chars: ',│`|:"'' ()[]{}<>'

  # When set to `true`, selected text will be copied to the primary clipboard.
  save_to_clipboard: true

cursor:
  # Cursor style
  #
  # Values for 'style':
  #   - ▇ Block
  #   - _ Underline
  #   - | Beam
  style: Block

  # If this is `true`, the cursor will be rendered as a hollow box when the
  # window is not focused.
  unfocused_hollow: true

# Live config reload (changes require restart)
live_config_reload: true
# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#shell:
#  program: /bin/bash
#  args:
#    - --login

# Mouse bindings
#
# Mouse bindings are specified as a list of objects, much like the key
# bindings further below.
#
# To trigger mouse bindings when an application running within Alacritty captures the mouse, the
# `Shift` modifier is automatically added as a requirement.
#
# Each mouse binding will specify a:
#
# - `mouse`:
#
#   - Middle
#   - Left
#   - Right
#   - Numeric identifier such as `5`
#
# - `action` (see key bindings)
#
# And optionally:
#
# - `mods` (see key bindings)
#mouse_bindings:
#  - { mouse: Middle, action: PasteSelection }

# Key bindings
#
# Key bindings are specified as a list of objects. For example, this is the
# default paste binding:
#
# `- { key: V, mods: Control|Shift, action: Paste }`
#
# Each key binding will specify a:
#
# - `key`: Identifier of the key pressed
#
#    - A-Z
#    - F1-F24
#    - Key0-Key9
#
#    A full list with available key codes can be found here:
#    https://docs.rs/glutin/*/glutin/event/enum.VirtualKeyCode.html#variants
#
#    Instead of using the name of the keys, the `key` field also supports using
#    the scancode of the desired key. Scancodes have to be specified as a
#    decimal number. This command will allow you to display the hex scancodes
#    for certain keys:
#
#       `showkey --scancodes`.
#
# Then exactly one of:
#
# - `chars`: Send a byte sequence to the running application
#
#    The `chars` field writes the specified string to the terminal. This makes
#    it possible to pass escape sequences. To find escape codes for bindings
#    like `PageUp` (`"\x1b[5~"`), you can run the command `showkey -a` outside
#    of tmux. Note that applications use terminfo to map escape sequences back
#    to keys. It is therefore required to update the terminfo when changing an
#    escape sequence.
#
# - `action`: Execute a predefined action
#
#   - ToggleViMode
#   - Copy
#   - Paste
#   - PasteSelection
#   - IncreaseFontSize
#   - DecreaseFontSize
#   - ResetFontSize
#   - ScrollPageUp
#   - ScrollPageDown
#   - ScrollHalfPageUp
#   - ScrollHalfPageDown
#   - ScrollLineUp
#   - ScrollLineDown
#   - ScrollToTop
#   - ScrollToBottom
#   - ClearHistory
#   - Hide
#   - Minimize
#   - Quit
#   - ToggleFullscreen
#   - SpawnNewInstance
#   - ClearLogNotice
#   - ClearSelection
#   - ReceiveChar
#   - None
#
#   (`mode: Vi` only):
#   - Open
#   - Up
#   - Down
#   - Left
#   - Right
#   - First
#   - Last
#   - FirstOccupied
#   - High
#   - Middle
#   - Low
#   - SemanticLeft
#   - SemanticRight
#   - SemanticLeftEnd
#   - SemanticRightEnd
#   - WordRight
#   - WordLeft
#   - WordRightEnd
#   - WordLeftEnd
#   - Bracket
#   - ToggleNormalSelection
#   - ToggleLineSelection
#   - ToggleBlockSelection
#   - ToggleSemanticSelection
#
#   (macOS only):
#   - ToggleSimpleFullscreen: Enters fullscreen without occupying another space
#
#   (Linux/BSD only):
#   - CopySelection: Copies into selection buffer
#
# - `command`: Fork and execute a specified command plus arguments
#
#    The `command` field must be a map containing a `program` string and an
#    `args` array of command line parameter strings. For example:
#       `{ program: "alacritty", args: ["-e", "vttest"] }`
#
# And optionally:
#
# - `mods`: Key modifiers to filter binding actions
#
#    - Command
#    - Control
#    - Option
#    - Super
#    - Shift
#    - Alt
#
#    Multiple `mods` can be combined using `|` like this:
#       `mods: Control|Shift`.
#    Whitespace and capitalization are relevant and must match the example.
#
# - `mode`: Indicate a binding for only specific terminal reported modes
#
#    This is mainly used to send applications the correct escape sequences
#    when in different modes.
#
#    - AppCursor
#    - AppKeypad
#    - Alt
#
#    A `~` operator can be used before a mode to apply the binding whenever
#    the mode is *not* active, e.g. `~Alt`.
#
# Bindings are always filled by default, but will be replaced when a new
# binding with the same triggers is defined. To unset a default binding, it can
# be mapped to the `ReceiveChar` action. Alternatively, you can use `None` for
# a no-op if you do not wish to receive input characters for that binding.
#
# If the same trigger is assigned to multiple actions, all of them are executed
# at once.
#key_bindings:
#- { key: Paste,                                action: Paste          }
#- { key: Copy,                                 action: Copy           }
#- { key: L,         mods: Control,             action: ClearLogNotice }
#- { key: L,         mods: Control, mode: ~Vi,  chars: "\x0c"          }
#- { key: PageUp,    mods: Shift,   mode: ~Alt, action: ScrollPageUp,  }
#- { key: PageDown,  mods: Shift,   mode: ~Alt, action: ScrollPageDown }
#- { key: Home,      mods: Shift,   mode: ~Alt, action: ScrollToTop,   }
#- { key: End,       mods: Shift,   mode: ~Alt, action: ScrollToBottom }

# Vi Mode
#- { key: Space,  mods: Shift|Control, mode: Vi, action: ScrollToBottom          }
#- { key: Space,  mods: Shift|Control,           action: ToggleViMode            }
#- { key: Escape,                      mode: Vi, action: ClearSelection          }
#- { key: I,                           mode: Vi, action: ScrollToBottom          }
#- { key: I,                           mode: Vi, action: ToggleViMode            }
#- { key: Y,      mods: Control,       mode: Vi, action: ScrollLineUp            }
#- { key: E,      mods: Control,       mode: Vi, action: ScrollLineDown          }
#- { key: G,                           mode: Vi, action: ScrollToTop             }
#- { key: G,      mods: Shift,         mode: Vi, action: ScrollToBottom          }
#- { key: B,      mods: Control,       mode: Vi, action: ScrollPageUp            }
#- { key: F,      mods: Control,       mode: Vi, action: ScrollPageDown          }
#- { key: U,      mods: Control,       mode: Vi, action: ScrollHalfPageUp        }
#- { key: D,      mods: Control,       mode: Vi, action: ScrollHalfPageDown      }
#- { key: Y,                           mode: Vi, action: Copy                    }
#- { key: Y,                           mode: Vi, action: ClearSelection          }
#- { key: Copy,                        mode: Vi, action: ClearSelection          }
#- { key: V,                           mode: Vi, action: ToggleNormalSelection   }
#- { key: V,      mods: Shift,         mode: Vi, action: ToggleLineSelection     }
#- { key: V,      mods: Control,       mode: Vi, action: ToggleBlockSelection    }
#- { key: V,      mods: Alt,           mode: Vi, action: ToggleSemanticSelection }
#- { key: Return,                      mode: Vi, action: Open                    }
#- { key: K,                           mode: Vi, action: Up                      }
#- { key: J,                           mode: Vi, action: Down                    }
#- { key: H,                           mode: Vi, action: Left                    }
#- { key: L,                           mode: Vi, action: Right                   }
#- { key: Up,                          mode: Vi, action: Up                      }
#- { key: Down,                        mode: Vi, action: Down                    }
#- { key: Left,                        mode: Vi, action: Left                    }
#- { key: Right,                       mode: Vi, action: Right                   }
#- { key: Key0,                        mode: Vi, action: First                   }
#- { key: Key4,   mods: Shift,         mode: Vi, action: Last                    }
#- { key: Key6,   mods: Shift,         mode: Vi, action: FirstOccupied           }
#- { key: H,      mods: Shift,         mode: Vi, action: High                    }
#- { key: M,      mods: Shift,         mode: Vi, action: Middle                  }
#- { key: L,      mods: Shift,         mode: Vi, action: Low                     }
#- { key: B,                           mode: Vi, action: SemanticLeft            }
#- { key: W,                           mode: Vi, action: SemanticRight           }
#- { key: E,                           mode: Vi, action: SemanticRightEnd        }
#- { key: B,      mods: Shift,         mode: Vi, action: WordLeft                }
#- { key: W,      mods: Shift,         mode: Vi, action: WordRight               }
#- { key: E,      mods: Shift,         mode: Vi, action: WordRightEnd            }
#- { key: Key5,   mods: Shift,         mode: Vi, action: Bracket                 }

# (Windows, Linux, and BSD only)
#- { key: V,        mods: Control|Shift,           action: Paste            }
#- { key: C,        mods: Control|Shift,           action: Copy             }
#- { key: C,        mods: Control|Shift, mode: Vi, action: ClearSelection   }
#- { key: Insert,   mods: Shift,                   action: PasteSelection   }
#- { key: Key0,     mods: Control,                 action: ResetFontSize    }
#- { key: Equals,   mods: Control,                 action: IncreaseFontSize }
#- { key: Add,      mods: Control,                 action: IncreaseFontSize }
#- { key: Subtract, mods: Control,                 action: DecreaseFontSize }
#- { key: Minus,    mods: Control,                 action: DecreaseFontSize }

# (Windows only)
#- { key: Return,   mods: Alt,           action: ToggleFullscreen }

# (macOS only)
#- { key: K,      mods: Command, mode: ~Vi, chars: "\x0c"            }
#- { key: Key0,   mods: Command,            action: ResetFontSize    }
#- { key: Equals, mods: Command,            action: IncreaseFontSize }
#- { key: Add,    mods: Command,            action: IncreaseFontSize }
#- { key: Minus,  mods: Command,            action: DecreaseFontSize }
#- { key: K,      mods: Command,            action: ClearHistory     }
#- { key: V,      mods: Command,            action: Paste            }
#- { key: C,      mods: Command,            action: Copy             }
#- { key: C,      mods: Command, mode: Vi,  action: ClearSelection   }
#- { key: H,      mods: Command,            action: Hide             }
#- { key: M,      mods: Command,            action: Minimize         }
#- { key: Q,      mods: Command,            action: Quit             }
#- { key: W,      mods: Command,            action: Quit             }
#- { key: N,      mods: Command,            action: SpawnNewInstance }
#- { key: F,      mods: Command|Control,    action: ToggleFullscreen }
